# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ipscanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyrebase


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 165)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.ip1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip1.setGeometry(QtCore.QRect(10, 30, 231, 20))
        self.ip1.setObjectName("ip1")
        self.reset1 = QtWidgets.QPushButton(self.centralwidget)
        self.reset1.setGeometry(QtCore.QRect(250, 30, 75, 23))
        self.reset1.setObjectName("reset1")
        self.reset1.clicked.connect(self.buka1)
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.ip2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip2.setGeometry(QtCore.QRect(10, 80, 231, 20))
        self.ip2.setObjectName("ip2")
        self.reset2 = QtWidgets.QPushButton(self.centralwidget)
        self.reset2.setGeometry(QtCore.QRect(250, 80, 75, 23))
        self.reset2.setObjectName("reset2")
        self.reset2.clicked.connect(self.buka2)
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 211, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def buka1(self):
        config = {
            "apiKey" : "AIzaSyAi07PxKD1_L4SSQ5-vEn0aRXImV77glGk",
            "authDomain" : "kalori-makanan.firebaseapp.com",
            "databaseURL" : "https://kalori-makanan.firebaseio.com/",
            "storageBucket": "kalori-makanan.appspot.com"
            }

        firebase = pyrebase.initialize_app(config)

        db = firebase.database()

        a = db.child("IP").get()
        self.ip1.setText(str(a.val()))
        print(a.val())
        
    def buka2(self):
        config = {
            "apiKey" : "AIzaSyAi07PxKD1_L4SSQ5-vEn0aRXImV77glGk",
            "authDomain" : "kalori-makanan.firebaseapp.com",
            "databaseURL" : "https://kalori-makanan.firebaseio.com/",
            "storageBucket": "kalori-makanan.appspot.com"
            }

        firebase = pyrebase.initialize_app(config)

        db = firebase.database()

        a = db.child("IP1").get()
        self.ip2.setText(str(a.val()))
        print(a.val())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP Scanner"))
        self.label.setText(_translate("MainWindow", "IP CAMERA 1"))
        self.reset1.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "IP CAMERA 1"))
        self.reset2.setText(_translate("MainWindow", "Open"))
        self.label_3.setText(_translate("MainWindow", "Catatan: Reset perangkat terlebih dahulu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
